# Artificial Neural Network

### Importing the libraries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

## Part 1 - Data Preprocessing

### Importing the dataset

In [28]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [30]:
print(dataset)

      RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMemb

In [29]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [5]:
print(y)

[1 0 1 ... 1 1 0]


### Encoding categorical data

Label Encoding the "Gender" column

In [6]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [7]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One Hot Encoding the "Geography" column

In [8]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [9]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### Splitting the dataset into the Training set and Test set

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

### Feature Scaling

In [11]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Part 2 - Building the ANN

### Initializing the ANN

In [12]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [13]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [14]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [15]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## Part 3 - Training the ANN

### Compiling the ANN

In [16]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

### Training the ANN on the Training set

In [17]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 110)

Epoch 1/110


250/250 [==============================] - 1s 1ms/step - loss: 0.5818 - accuracy: 0.7121
Epoch 2/110
250/250 [==============================] - 0s 983us/step - loss: 0.4753 - accuracy: 0.7966
Epoch 3/110
250/250 [==============================] - 0s 937us/step - loss: 0.4553 - accuracy: 0.7974
Epoch 4/110
250/250 [==============================] - 0s 993us/step - loss: 0.4443 - accuracy: 0.7999
Epoch 5/110
250/250 [==============================] - 0s 978us/step - loss: 0.4364 - accuracy: 0.8020
Epoch 6/110
250/250 [==============================] - 0s 972us/step - loss: 0.4305 - accuracy: 0.8034
Epoch 7/110
250/250 [==============================] - 0s 1ms/step - loss: 0.4255 - accuracy: 0.8069
Epoch 8/110
250/250 [==============================] - 0s 1ms/step - loss: 0.4207 - accuracy: 0.8133
Epoch 9/110
250/250 [==============================] - 0s 1ms/step - loss: 0.4171 - accuracy: 0.8181
Epoch 10/110
250/250 [==============================] - 0s 1ms/step - loss: 0.4

250/250 [==============================] - 0s 988us/step - loss: 0.3332 - accuracy: 0.8633
Epoch 77/110
250/250 [==============================] - 0s 943us/step - loss: 0.3331 - accuracy: 0.8622
Epoch 78/110
250/250 [==============================] - 0s 916us/step - loss: 0.3329 - accuracy: 0.8631
Epoch 79/110
250/250 [==============================] - 0s 964us/step - loss: 0.3330 - accuracy: 0.8625
Epoch 80/110
250/250 [==============================] - 0s 1ms/step - loss: 0.3333 - accuracy: 0.8626
Epoch 81/110
250/250 [==============================] - 0s 1ms/step - loss: 0.3331 - accuracy: 0.8626
Epoch 82/110
250/250 [==============================] - 0s 1ms/step - loss: 0.3330 - accuracy: 0.8631
Epoch 83/110
250/250 [==============================] - 0s 933us/step - loss: 0.3326 - accuracy: 0.8648
Epoch 84/110
250/250 [==============================] - 0s 938us/step - loss: 0.3327 - accuracy: 0.8619
Epoch 85/110
250/250 [==============================] - 0s 987us/step - loss: 0.333

## Part 4 - Making the predictions and evaluating the model

### Predicting the result of a single observation

In [23]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

1/1 [==============================] - 0s 16ms/step
[[False]]


In [27]:
print(ann.predict(sc.transform([[0, 1, 0, 750, 1, 10, 3, 80000, 2, 1, 1, 20000]])) > 0.5)

1/1 [==============================] - 0s 16ms/step
[[False]]


### Predicting the Test set results

In [20]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

63/63 [==============================] - 0s 789us/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Making the Confusion Matrix

In [21]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1525   70]
 [ 207  198]]


0.8615